---
title: 'Class 6: R Functions'
author: "Ezequiel Quevedo"
date: "4/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# About
## About
### About
This is my **class 6** r markdown document with my *code* and notes for the day. 

```{r, echo=FALSE}
plot(1:10, typ = "l", col = "blue")
```




## Reading in files

There are 3 files to read:
https://bioboot.github.io/bimm143_S19/class-material/test1.txt
https://bioboot.github.io/bimm143_S19/class-material/test2.txt
https://bioboot.github.io/bimm143_S19/class-material/test3.txt

```{r}
read.csv("test1.txt")
```

```{r}
read.table("test2.txt", sep = "$", header = TRUE)
```

```{r}
read.table("test3.txt")
```

```{r}
read.csv("https://bioboot.github.io/bimm143_S19/class-material/test1.txt")
```


## Funtions

Our first silly function example:
```{r}
add <- function(x, y = 1) {
  #sum the input plus 1
  x + y
}
```

```{r}
add(1:3)
add(1:3, 4)
add(1:3, TRUE)
add(1:3, FALSE)
# add(1, 2, 2)
# add(x = 3, y = "2")
```

# Turning a frequently used code into a function
```{r}
## You need a “name”, “arguments” and “body”…
rescale <- function(x) {
  rng <- range(x, na.rm = TRUE)
  (x - rng[1]) / (rng[2] - rng[1])
}
# Test on a small example where you know the answer
rescale(1:10)
```

```{r}
rescale( c(1, 2, NA, 3, 10))

```
```{r}
#rescale( c(1, 10, "string"))

```

```{r}
x <- c(1, 2, NA, 3, 10)
  rng <- range(x, na.rm = TRUE)
  (x - rng[1]) / (rng[2] - rng[1])
```

```{r}
rescale2 <- function(x, na.rm = TRUE) {
  rng <- range(x, na.rm = na.rm)
  (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale2(1:10)
```

```{r}
rescale3 <- function(x, na.rm = TRUE, plot = FALSE) {
  rng <- range(x, na.rm = na.rm)
  print("Hello")
  
  answer <- (x - rng[1]) / (rng[2] - rng[1])
  
  print(answer)
  
  print("is it me you are looking for?")

  if(plot) {
    plot(answer, typ = "b", lwd = 4)
    print("Please don't sing again")
  }
print("I can see it in ...")
return(answer)
}
```
```{r}
rescale3( c(1, 3, NA, 10))
```
```{r}
rescale3( c(1, 3, NA, 10), plot = TRUE)

```

